name: Run Tests

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.5.2'

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test